### ISSUE TITLE
Re-use semantic in active handlers

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1016]
**What Needs to be Done?**

When VT delivers a message to a handler it might be reusable depending on if it's a broadcast to a collection or a send of a handler. By default disallow and catch at runtime re-use of messages from handlers. Add new API call to taking ownership of message that either copies on demand or transfers ownership. Ensure that access to the message, if ownership is transferred, does not occur after the handler runs (e.g., user changing epoch and the system reading the wrong one after).

**Comment by pnstickne** [comment]
On all sendMsg/broadcastMsg, envelopes enter a 'locked' state. It is an error to change key properties (eg. dest, type, or handler) when locked. Since the envelope information is copied on transmit, this locked state is also the state of all incoming messages.

Thus for a handler to be able to send/broadcast a message, or use it as such, it must explicit unlock the envelope.
This explicit operation indicates intent. No changes to lifetime are done.
