### ISSUE TITLE
Stats output failing on release

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1235]
**Describe the bug**
Explore solutions for dumping without increasing memory usage.

**Comment by nlslatt** [comment]
vt develop stores a small number of phases (lookback) worth of stats, dumping the most recent phase stats to file from `finishedLB`.  The lookback (instead of a full clear or near full clear) was necessary for some of the load models to work correctly anyway.  We could/should probably do something similar for the release branch if such load models exist on it.

**Comment by nlslatt** [comment]
Stats outputs are currently turned off at compile time in the release branch because the stats build up throughout the run and are only dumped at the very end.  I'm the only one using stats files right now (accepting this limitation), so this can wait for 1.0.2.

**Comment by lifflander** [comment]
I think we can close this as customers are using releases from develop now which shouldn't have this problem.
