### ISSUE TITLE
Remove post-migration O_l statistic calculation

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1295]
**What Needs to be Done?**

It's not useful because it doesn't change after migration.

**Comment by PhilMiller** [comment]
If we extend things to consider heterogeneous nodes, the calculation could potentially differ depending on assignment. It's probably fine to disregard that for now, and add the capability back in if/when it becomes salient.

**Comment by nlslatt** [comment]
> If we extend things to consider heterogeneous nodes, the calculation could potentially differ depending on assignment. It's probably fine to disregard that for now, and add the capability back in if/when it becomes salient.

How would that change a calculation based on measured loads?  We aren't rerunning anything to see how the object load differs on the destination rank.  Were you thinking of having some heuristic that scales the previously measured loads based on where they are migrated?

**Comment by PhilMiller** [comment]
If the calculation of O_l is from a call to the load model, then that could be written to do a node-specific calculation, yeah.

**Comment by nlslatt** [comment]
> If the calculation of O_l is from a call to the load model, then that could be written to do a node-specific calculation, yeah.

It does use a call into the load model, which is why it's breaking for me (my load model longer has access to the loads of objects that were migrated off node because I'm storing the loads in the collection elements themselves).  For use with heterogeneous nodes, it seems like it might be more appropriate to call into the load model at the new location.  Is that true?  I guess it would need to know something about both the old and new node in order to scale the load.  Computing the post-migration `O_l` on the new node would solve my problem just as well as removing the calculation would.

**Comment by PhilMiller** [comment]
If it's easy to change it to make the `O_l` calculation on the new node, could we go with that?

**Comment by nlslatt** [comment]
> If it's easy to change it to make the `O_l` calculation on the new node, could we go with that?

I think making that work is closely related to #1127.  We would have to rewrite history in `NodeStats`, effectively, so that the load model would see the collection elements that are now on node instead of what was on node at the time the phase in question was executed.

**Comment by nlslatt** [comment]
I see now that the post-migration `O_l` calculation actually races with migration right now.  We'll have to fix that.

**Comment by nlslatt** [comment]
Due to the refactor a long time ago to use ProposedMigrations, this doesn't seem relevant anymore.
