### ISSUE TITLE
Move migration functionality out of BaseLB

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1568]
**What Needs to be Done?**

Related to issue comment https://github.com/DARMA-tasking/vt/issues/1559#issuecomment-928354276. We want LBManager to actually perform the migrations to make BaseLB more functional.

**Comment by nlslatt** [comment]
I'm thinking we might want to create a new object group called `ObjectDistribution`. A separate instance of it can be constructed for each LB strategy that will be called. It would be initialized to know the pre-LB object distribution and could be operated on to get the LB statistics (either by using a specialized load model or by changing the `RawData` model to always use an `ObjectDistribution`). The LB strategy would call `migrateObjectTo` on the `ObjectDistribution` instead of on `BaseLB`. The `ObjectDistribution` would communicate so that both ranks directly involved in a migration (regardless of who requested the migration) would know about the proposed change to the object distribution. When the effectiveness of the LB strategy has been evaluated, the winning `ObjectDistribution` object group would be told to realize its proposed migrations.

**Comment by nlslatt** [comment]
Expanding on the above, each `ObjectDistribution` instance could hold its own `StatsData` instance that it updates to account for proposed migrations. It could use the same load model as is used for the pre-LB statistics if we call `setLoads` on the model using the members of the `StatsData` object owned by the `ObjectDistribution` instead of by `NodeStats`. If we used the same instance of a load model and not a copy, we'd need to switch which data it operates on at least twice a phase, more if we're comparing multiple LBs. What do you think, @lifflander and @PhilMiller?
