### ISSUE TITLE
Write polymorphic collection example

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#2005]
**What Needs to be Done?**

- [ ] First do this
- [ ] Then do that.
- [ ] Also this other thing.

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by PhilMiller** [comment]
An important design question here: do we expect handlers implemented by virtual methods to dispatch based on the dynamic type of the recipient object? I don't think we can, because we necessarily capture and register the pointer to the base class implementation.

Given that, I think we need to document that limitation, and hopefully figure out some way to warn or error on it at compile time
