### ISSUE TITLE
Reduce unnecessary header file inclusion to speed up builds

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#247]

**Comment by pnstickne** [comment]
LLVM project says only use guard approach as optimizations to it (and speed of modern disks, eg.) reduce benefit of pragma-once (old MSVC was bad a guard optimizations .. a very long time ago). Would probably be good to lint guards + use a domain prefix VT_.._H, eg; doesn't address any potential performance issues. While it's easy to switch between the methods, Cray C++ (if such is ever a target) does not currently have pragma-once.

Could switch from header-includes to forward declares when possible (ie. when only return types through decl.), although overall usages of such are probably hampered by templates.

The actual VT itself seems to 'compile within not too unreasonable time'; largely test and examples take over the local build duration.. if usages are complaining about long build times when USING VT, then probably need to pair down templates / imports in those cases instead of core. Might also be able to separate public and private headers.

**Comment by PhilMiller** [comment]
Cray C++ is not a current target, but it's certainly conceivable.

**Comment by lifflander** [comment]
@PhilMiller @pnstickne Should I close this issue?

**Comment by lifflander** [comment]
Closing this issue as it is too vague.
