### ISSUE TITLE
Distinct method to explicitly identify send() to objects on same process

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#585]
We should implement an analogue to `send<>()` methods with the added specification that the sender and recipient handler run on the same process. I propose calling this `schedule()`, or maybe `sendLocal()`.

I see at least a few prospective benefits from this
* We can reduce some overheads from object location when the recipient is an element of a migratable collection
* We can omit inaccurate records of apparent communication that will always be local from load balancing statistics
* We can assert the accuracy of the call actually being local, to detect logic errors

**Comment by lifflander** [comment]
There is a slight edge case to be addressed---if the recipient object were to migrate while the message is in the scheduler. Either we say this is invalid or address a promotion to non-local.

I think we could address this issue and make this cheaper by holding a location manager delivery lambda in the scheduler rather than a virtual collection send lambda. This should be fairly easy---we can add a *schedule-for-later* flag to the location manager when asking for delivery of a message.

**Comment by pnstickne** [comment]
Less lambdas, more .. mm, contracts? Lambdas x T are 'not cheap' compilation concerns.

**Comment by PhilMiller** [comment]
I want to say migration while such a message is queued should be invalid.

**Comment by pnstickne** [comment]
@PhilMiller What about a `send` that has all such same-node short-circuiting in place, with a `schedule` simply being a version that asserts (and implicitly sends to the same node)?

**Comment by PhilMiller** [comment]
@pnstickne Yes, that's exactly what I'm looking for.

**Comment by lifflander** [comment]
@pnstickne @PhilMiller 

 This brings up an interesting user-interface concern of whether messages should be serialized or not when locally sent. Currently, this isn't clearly defined to the user. I would like that to be a trait on the message potentially or otherwise well defined. This is popped up as a bug in EMPIRE, expecting data in a message (Kokkos::View) to be copied when it wasn't causing problems.

I like the idea to have a code path dedicated to local sends. Also, currently the `ActiveMessenger` doesn't allow local sends. This is a pain in the ass because you have to invoke the handler yourself, with can lead to other issues. No clear way to schedule that operation for the future.

Also, on the idea for schedule for the future, I would like to be able to hold simple message schedule operations without a lambda. In some cases, just a `MsgPtr` is sufficient. We also might want some ID that activates a component with a context.

**Comment by PhilMiller** [comment]
You could potentially use const-ness of message members to indicate
necessity of serialization in locally-delivered messages. That's only a
one-way signal, though, that the recipient won't modify something that the
sender might later reference. It doesn't guarantee that the sender won't
modify it before the recipient consumes it.

**Comment by lifflander** [comment]
> You could potentially use const-ness of message members to indicate necessity of serialization in locally-delivered messages. That's only a one-way signal, though, that the recipient won't modify something that the sender might later reference. It doesn't guarantee that the sender won't modify it before the recipient consumes it.
> […](#)

I like the idea of having const-ness for members to determine that. We should be able to detect such a property fairly easily with an overload.

**Comment by lifflander** [comment]
I think we have most of this issue addressed in various ways from other issues. We don't see a strong need for explicit user local sends.
