### ISSUE TITLE
Start using "rang" library for clear, platform-independent colorized terminal output

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#858]
**What Needs to be Done?**

The `rang` library provides colorized terminal output in a header-only form with a very permissive license. Let's swallow it up in `vt/lib` and clean up all the color output code.

https://github.com/agauniyal/rang

**Comment by PhilMiller** [comment]
Do some tests of compiler compatibility before jumping into implementation.
No good to waste time on it to find that it's hopelessly broken on Intel or
Nvidia.

**Comment by pnstickne** [comment]
The colorizing code bleeds everywhere through macros, so it becomes a global/leaked dep.

**Comment by pnstickne** [comment]
@lifflander rang "probably" won't work without modification due to using `isatty(fileno(stdout))` etc. That returns false in (most/all) MPI implementations .. per the fun little no-color effect I added for a bit :|

Is there a specific goal for this? Could definitely pull in features and/or do some cleanup.

**Comment by lifflander** [comment]
Not a very specific goal, but mostly to make the colorization more platform independent. Probably should be low priority though.

**Comment by lifflander** [comment]
Doesn't seem like a real problem now.
