### ISSUE TITLE
Remove distinction between temporary and permanent object IDs in load balancing

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#868]
**What Needs to be Done?**

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by PhilMiller** [comment]
Ideally, the IDs would be bijective with the pair {collection ID, index}

**Comment by PhilMiller** [comment]
@jstrzebonski I'll get more details filled in on this for you later today.

**Comment by PhilMiller** [comment]
I worked through part of the implementation #1017, and ran into the somewhat expected barrier over the use of the ability to extract current node assignments for each object in `objGetNode`.

The coupled bits of code that run into trouble with this are `BaseLB, GreedyLB, ZoltanLB, LBCommKey, and CollectionManager::recordStats`

**Comment by PhilMiller** [comment]
I think some of those usages could be done away with, or have an alternative data source that would give the relevant current node for the object in question.

**Comment by nlslatt** [comment]
My branch for removing temporary IDs is `868-remove-temporary-ids`.  I'll try to look at this a bit more on Monday before I'm out.

**Comment by nlslatt** [comment]
@jliffla I'm ready to hand this off.  What I've pushed on `868-remove-temporary-ids` almost builds.  I'm not sure I understand `test_model_comm_overhead.nompi.cc` well enough not to break it. I also haven't attempted to update `ZoltanLB` because you said you were the best person to tackle that.

I left the unique ID part of the struct the same as the old permanent ID, which had bits encoding the rank.  There shouldn't be any logic remaining that depends on those bits, so any alternative means of making the IDs unique across ranks should work fine.

**Comment by nlslatt** [comment]
@lifflander I made a comment to you above but messed up your name, so I'm not sure if you were notified.
