### ISSUE TITLE
Implement PhaseManager to refactor functionality out of LBManager

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#875]
**What Needs to be Done?**

The `LBManager` does a set of phase-related functions (things that happen when a new phase starts), which isn't really its responsibility. The new `PhaseManager` should make appropriate calls to operations scheduled on phase boundaries, including:
- LB invocation
- LB stats output
- LB stats trimming
- trace en/disablement
- Trace flushing
- memory usage printing
- runtime system diagnostics/stats processing

**Comment by PhilMiller** [comment]
As part of this, we want to think about what the API should be for moving from one phase to the next. Jonathan and I think the simplest and most obviously useful, but perhaps less-than-fully-general, is a global collective call along the lines of `thePhase()->nextPhaseCollective()` that every process must call in a synchronized collective fashion.

**Comment by lifflander** [comment]
Agreed. I think a simple collective call for the next phase is probably the easiest for apps to use and for us to manage in the runtime.

This means that `nextPhase`, `startPhaseRooted`, `proxy.LB`, and `proxy.LBsync` should all be removed in favor of the new API. Examples and test will need to be adjusted.

**Comment by PhilMiller** [comment]
Do you mind if I take this over and start implementation? It seems like the best way to address #1055, and unblocks some other work in NimbleSM as well.

**Comment by JacobDomagala** [comment]
It's fine for me, I'm still finishing work on #1024 so i wasn't able to start working on this.

**Comment by PhilMiller** [comment]
Design thoughts on the LB bits:
- No matter what, the planned phase manager might need to tell the collection manager to tell every collection about the phase transition, so that stats get recorded correctly. Alternately, we replace uses of `ElmStats::getPhase()` and its underlying member `ElmStats::cur_phase_` with a call to`thePhase()->getCurrentPhase()`, and stop keeping track within elements entirely. That would increase the sense of a single point of truth in the sytem.
- If we need LB stats for either of output or LB execution, then the above broadcast still needs to happen so that `theNode()->addNodeStats()` call in `ElmStats::syncNextPhase` happens
- Execution of LB or stats output needs to happen after all the stats are accumulated; stats trimming needs to happen after both of those.
- Should memory usage perhaps be recorded both pre- and post- phase transition, so that we can any effect of LB on it?

**Comment by PhilMiller** [comment]
From discussion on call:
- Manage subphases too,
- abstract callbacks instead of fixed function,
- control file subsume LB and tracing files

**Comment by PhilMiller** [comment]
The desire for abstract callbacks and hence potential arbitrary insertions is bolstered by a use case from Keita and Nic's resilience project.

**Comment by PhilMiller** [comment]
If we have hooks for various callbacks to be triggered, there should possibly be a distinction between the "end of phase N" trigger, and the "beginning of phase N+1" trigger.

**Comment by lifflander** [comment]
I'm going to take the first hack at this to sketch out an interface.
