### ISSUE TITLE
Make broadcasts deliver to the sender

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#883]
**What Needs to be Done?**

Right now, vt broadcasts over certain sets of recipients exclude the sender from having the handler called (general handler bcast, objgroup bcast, I think?) while broadcasts to collections go to all elements, even if the sender is an element. I think this may be an undesirable semantic inconsistency, depending on what callers do relative to this non-uniformity.

We should go over broadcast call sites, and see how this impacts callers. Do they all just call the handler in-line? Does this represent an issue of processing order, since all other recipients will have the broadcasts ordered by the root? Are they all doing something special, such that they really shouldn't receive the broadcast?

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by PhilMiller** [comment]
If this gets changed, remember to update docs/md/vt.md  as well

**Comment by lifflander** [comment]
We should carefully audit the AM bcast callsites to see. I think most of them run the handler locally after broadcasting.

Objgroup broadcasts go to all the nodes including the sender of the broadcast. So that is another motivation to fix this problem to make it more consistent.

I don't think there's a processing order issue here, unless we rely on that local call to happen right away. We should check for that at the callsites also.

I think the fix should just put it in the scheduler's queue so it gets prioritized properly.

**Comment by lifflander** [comment]
@pnstickne

**Comment by lifflander** [comment]
@JacobDomagala Can you work on this when you are done with your current issues?
