### ISSUE TITLE
Remove old, unused LB instrumentation data structures

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#992]
Remove all the old load balancing infrastructure that is not used. When I started implementing LB, I sketched out some implementation in `vt/src/vt/lb/*`. I believe none of this code is active or used. Try to remove it and ensure none of it is used anywhere.

**Comment by JacobDomagala** [comment]
It seems that only **`vt/src/vt/lb/migration/lb_migratable.h`** is used (**`HasMigrate`** struct is base struct for **`UntypedCollection`**) I suggest we either move the file or the **`HasMigrate`** struct declaration to **`vt/src/vt/vrt/collection*`** directory. 

NOTE: There's mention of this interface in **`vt/src/vt/vrt/collection/types/migratable.h:91`** together with explanation how it's supposed to be used. Not sure if we want to touch it, just wanted to point that out since there's **_@todo_** added to it.


What's your opinion @lifflander  @PhilMiller
